### ISSUE TITLE
private-build2 branch issue fter RESET FACTORY / ALL 

### ISSUE THREAD

**Issue by macfly1202** [thess/Prusa-Firmware#3] opened 2017-12-20 16:21 UTC
Hi, I would like submit a bug. I have done a total RESET FACTORY of my MK2S MMU this morning. I compile "your" firmware from branch private-build2 (that I compiled with Travis, like you) thren burn with Prusa upgrade firmware tools. Everything got ok during firmware process upgrade. Then, I do total step from 'wizard setup', with first layer calibration without issue. On the first print (then all the print), firmware crash just when making the first z-height calibration point. Strange characters appear on screen and only reboot is possible.

I redo 3 times and always the same issue at the same step.

Then, I redo a Factory Reset ALL. Flashed last prusa official released firmware from 2017-11-12. Do calibration. Do print without issue. 

Then I decided to reflash your firmware I initially test  without RESET FACTORY (your last one from private-build2 branch). Flashing was ok. And for printing : no issue at all, even where the same firmware was crashing previously. 

So, as a conclusion, I suppose there is some parameter in EEPROM init that is not / missing in your firmware branch? I never test this before so honestly, perhaps it's there since a long time (really, who want to reset factory firmware that is working very well !)       

Hope it could help to increase the high quality of your work.

**Comment by thess** [comment] 2017-12-20 18:13
Thanks for your report -- I will look into this to see if I missed something.

**Comment by thess** [comment] 2017-12-20 21:55
I think that moving from Prusa firmware v3.0.12 or earlier without a RESET->ALL might cause some problems with the setup wizard. However, since RESET->ALL erases the entire EEPROM, you should have no upgrade problems. I hate to say you might have had a build or flash problem since the problem doesn't re-occur after 2nd re-flash. I tried a couple of RESET and re-flash scenarios without issue. Unfortunately, if there is some hidden problem with these scenarios on an MMU configuration, I am unable to test. There should be no EEPROM compatibility problems with models in v3.1.0.

I do see a future compatibility issue with how I use EEPROM for 8-point MBC which I will fix in the next release which I plan to provide in this repo.

FWIW - There is an undocumented (as yet) feature in my firmware that permits complete save/restore of the EEPROM to the SD card. Since it does no interpretation of the contents, I would only suggest using it with identical firmware versions. ``M767 S`` will save to EESAVE.HEX and ``M768 R`` will restore the same file and reset your machine. I save the EEPROM before switching to foreign/experimental firmwares or test settings and then have the ability to restore all the settings when I want to return to my good setup.

**Comment by macfly1202** [comment] 2017-12-20 22:35
Perhaps I wasn't clear enough because of my French-glish(!) so I prefer to
explain again Thess. (Thanks for taking time to answer)

Here the steps I do :
I do RESET FACTORY / ALL before flashing your firmware the 1st time. Bug
occurs.

Then

I do again RESET FACTORY / ALL, install last pusa-firmware, tested it
successfully and then, installed your firmware WITHOUT RESET FACTORY / ALL in
this case AND without calibration with your firmware.  No issue at all.

Your firmware pb2 seem to work correctly but when you launch print, on Z
height calibration immediately crash. Don't know if help to formulate
things again but perhaps. If I could help, don't hesitate.

(your EEPROM save feature is marvelous in dev situation - will try it
soon!)

Tomorrow (because go to bed now in France), I will try again with your last
Travis version that has been rebuild today (I see it quickly if not
mismatch)

**Comment by macfly1202** [comment] 2017-12-21 11:50
Hi, I try again today v3.1.0 r4. I reset factory / all. Then upload with prusa-uploader your firmware from your github release. Redo calibration xyz. When Try the calibration first layer, crash (garbage on screen)
![34822e4c-e113-4d98-98dc-40ab1ecc6240](https://user-images.githubusercontent.com/6387630/34254767-ea29bd66-e64d-11e7-8d86-69d1ad2afff8.jpeg)

Then, without reset factory / all, upgrade last release prusa firwmare. attempt to do the first layer calibration only : fail but this time message appear :    
![d0acb055-257c-4d89-8626-5a6ed4628d59](https://user-images.githubusercontent.com/6387630/34254772-f7be0dc4-e64d-11e7-927d-a6488c5e41b5.jpeg)

So, as a conclusion, Eeproom corruption / override allocated blocks seem obvious. Calibration step is not storing Z-Level / height of calibration point. 

So, again I reset factory / all, install last release official, do all calibration steps. Then reinstall your firmware without reset factory all. 

I forgot to mention one thing: after calibration with your firmware, and crash occur. I reboot and go into support menu to see result of calibration : for Y distance from min: 3 values are similar instead of my usual 1.49;1.57;1.65. (don't rember the display value that must be the default I suppose). Don't remenber about the skew if was correct or not. my measured skew is usually 0.02/0.04.

hope it helps and thank you !

**Comment by thess** [comment] 2017-12-21 14:21
First off, I had no problem with your descriptions of what you did and what happened. Your English is just great. My French is non-existent. I just have not been able to reproduce your problem.

Now, after reviewing the whole factory reset, re-flash, re-calibrate sequence and from just code inspection, I think the process where you first do a factory reset without immediately doing a new setup leaves the firmware EEPROM status somewhat inconsistent. I would strongly recommend that if you want to do a factory reset for new firmware, you should do it **after** you flash the update and then perform the complete setup.

Your note about the calibration data is of interest. I made a firmware change based on a discussion [here](https://github.com/prusa3d/Prusa-Firmware/issues/147) regarding XY skew compensation and print artifacts. I will check that out later today however, I do not think this to be the issue with the Z-offset not set properly - The fact that the first layer calibration did not complete may be triggering the problem - I'll look into that. I think the official Prusa firmware may have the same problem given that scenario.

And finally, I think I know why you get garbage on the screen instead of the correct message. I can fix that but you will still get "sensor triggered too high" message if the Z-offsets have not yet been stored. I have seen this arise independent of firmware version and corrected after doing a manual "Mesh Bed Leveling" from the LCD.

Thanks for all your time testing and reporting! :+1:

**Comment by macfly1202** [comment] 2017-12-21 14:47
A/ So, I will try right now to reset all again : 
1/ flash firmware 3.1.0rc4+ do calibration process after flash
2/ reset factory all. 

B/ about calibration data: I have seen this thread about artifacts last summer and was wondering if I had the same ... the fact is the first layer calibration did NOT start I want to say (instead of "did not complete"): at the first point, bam crash. Another point I see again, the nozzle touch the bed when launching this first layer calibration, just before the point height measurement. I will do a video if happen again with next reset process you suggest me.  

C/ will try  "Mesh Bed Leveling"  if happen again...

Next report after calibration in few minutes....

**Comment by thess** [comment] 2017-12-21 15:12
No need for a video - I have seen this behavior in the past with all versions - not nice.

It may be a matter of semantics - when I say "did not complete" and you say "did not start" we are both correct (sort of). The process starts when you push the button - In my mind it didn't complete - same thing.

**Comment by macfly1202** [comment] 2017-12-21 16:08
Here my report : 
1/ flashed firmware 3.1.0rc4+ do calibration process from wizard after flashing. Only first part sucessful because of "First layer calibration" crash as reported. then Reboot and :  
2/ do a reset factory / all.
3/ do calibration again with the wizard. Test ok, Calibration XYZ Ok, First layer calibration :  FAIL, exactly like step before...

"go back to departure line"... At this point, I'm sure this error is trivial and could not be solve without reinstalling the official firmware (or perhaps an anterior branch - didn't test)

**Comment by thess** [comment] 2017-12-24 00:19
I believe I now understand the problem you are observing and will have at least a partial fix though it doesn't solve the root cause of your problem. Here are a few comments on what has transpired.
- There are no EEPROM conflicts or corruption between my version and the official version
- The "crash" you are seeing with garbage on the screen was caused a minor problem in the LCD routine displaying the critical alert and reset message in my updated LCD support. This will be fixed in the next base-level.
- The message you saw using the stock Prusa firmware was the same result as the 3.1.0r4 version was trying to display. The cause is as follows:
  - The z-height calibration pass stores the offsets in EEPROM. That is the procedure when you raise the z-axis to top first.
  - If the offsets are stored in EEPROM then...
  - During the "mesh bed leveling" pass, the probe height at each point is compared with the values stored in EEPROM. If these comparisons show a absolute difference between the new probe and the one stored in EEPROM is greater than 1mm, you get this failure.
  - If the probed values are not previously stored, you will not see any probe failure messages of this type during MBL.

Executing "Mesh bed leveling" without previously executing "Calibrate Z" will not store the offsets.

All that said, my guess is you have a problem with the PINDA probe being loose or too high.

**Comment by macfly1202** [comment] 2017-12-24 08:05
Thanks thess taking time to have a look on this. 
Very clear explanation. My first reaction is : My pinda has not been move since 4 month and never another firmware from you or official give me this error. When I reinstall the official firmware, I haven't got this issue. Does it mean there could be a bug in official firmware that did not detect this error because not storing in eeprom first step Z top value you describe ? 

Perhaps it's my probe ? I could try to move it a litlle bit down but my correct Z live value is about -0.62 and seem to be a good value.

**Comment by macfly1202** [comment] 2017-12-25 18:16
Hi, Merry Christmas first. I try to redo full calibration after lowering a little (0.5mm) the PINDA. Calibration XYZ is ok but still got the error. 
In 'SUPPORT' menu : 'Y distance from min'i is 1.48mm for left, center and right. Same value! impossible! 
so Calibration is not storing value... 
I try to do Z calibration only before first layer calibration but still the same error probe I mention on the previous post. 
Do you think this error is due to MMU version?

**Comment by thess** [comment] 2018-02-27 20:46
@macfly1202 - I haven't forgotten you. There indeed was a serious bug in the way homing was treated when XY compensation was turned off - it is now optional.

I believe your issues with the Setup Wizard / XY calibration and screen corruption have been addressed in the latest version found here: https://github.com/thess/Prusa-Firmware/releases.

Re-open this if it still fails - if any other problems, please open a new issue.

**Closed as completed by thess** 2018-02-27 20:46 UTC

**Comment by macfly1202** [comment] 2018-02-27 21:48
Thank you very much Ted. Very kind to inform me ! I was just reading your bunch feature/debug in your latest package. Will test soon.

**Comment by macfly1202** [comment] 2018-03-03 09:03
Install this last release this morning and redo full calibration xyz: all passed successfully. Not test print yet but this is Nice job, one more time.

**Comment by macfly1202** [comment] 2018-03-03 20:46
Everything seems ok for now with this firmware. issue closed !

**Comment by macfly1202** [comment] 2018-03-04 08:49
My MK2S MMU is so happy this morning...I love your firmware : every thing is smooth...
![img_2820](https://user-images.githubusercontent.com/6387630/36943877-56ce2322-1f91-11e8-9768-c438aa563efd.JPG)
